Public Class DXF_Class
    Sub New(ByVal FileName As String)
        FileOpen(1, FileName, OpenMode.Output)
        PrintLine(1, 0)
        PrintLine(1, "SECTION")
        PrintLine(1, 2)
        PrintLine(1, "ENTITIES")
    End Sub
    Sub DXF_TEXT(ByVal P As RoadPoint)
        PrintLine(1, 0)
        PrintLine(1, "TEXT")
        PrintLine(1, 8)
        PrintLine(1, "TEXTS")
        PrintLine(1, 62)
        PrintLine(1, 4)
        PrintLine(1, 10)
        PrintLine(1, P.Y - 5)
        PrintLine(1, 20)
        PrintLine(1, P.X - 5)
        PrintLine(1, 40)
        PrintLine(1, 2)
        PrintLine(1, 1)
        PrintLine(1, P.Name)
        PrintLine(1, 7)
        PrintLine(1, "宋体")
    End Sub
    Sub DXF_Point(ByVal p As RoadPoint)
        PrintLine(1, 0)
        PrintLine(1, "POINT")
        PrintLine(1, 8)
        PrintLine(1, "POINTS")
        PrintLine(1, 62)
        PrintLine(1, 3)
        PrintLine(1, 10)
        PrintLine(1, p.Y)
        PrintLine(1, 20)
        PrintLine(1, p.X)
    End Sub
    Sub DXF_LINE(ByVal P1 As RoadPoint, ByVal P2 As RoadPoint)
        PrintLine(1, 0)
        PrintLine(1, "LINE")
        PrintLine(1, 8)
        PrintLine(1, "LINES")
        PrintLine(1, 62)
        PrintLine(1, 1)
        PrintLine(1, 10)
        PrintLine(1, P1.Y)
        PrintLine(1, 20)
        PrintLine(1, P1.X)
        PrintLine(1, 11)
        PrintLine(1, P2.Y)
        PrintLine(1, 21)
        PrintLine(1, P2.X)

    End Sub
    Sub DXF_Circle(ByVal p As RoadPoint)
        PrintLine(1, 0)
        PrintLine(1, "CIRCLE")
        PrintLine(1, 8)
        PrintLine(1, "CIRCLES")
        PrintLine(1, 62)
        PrintLine(1, 2)
        PrintLine(1, 10)
        PrintLine(1, p.Y)
        PrintLine(1, 20)
        PrintLine(1, p.X)
        PrintLine(1, 30)
        PrintLine(1, "0.0")
        PrintLine(1, 40)
        PrintLine(1, 2)
    End Sub
    Sub DXF_ED()
        PrintLine(1, 0)
        PrintLine(1, "ENDSEC")
        PrintLine(1, 0)
        PrintLine(1, "EOF")
        FileClose(1)
    End Sub
End Class
