# Generated by Django 2.1 on 2018-08-14 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='cmdb_employee',
        ),
    ]
